/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Configuration: typeof import('./src/components/Configuration.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LogView: typeof import('./src/components/LogView.vue')['default']
    OverView: typeof import('./src/components/OverView.vue')['default']
    RtData: typeof import('./src/components/RtData.vue')['default']
    TagsList: typeof import('./src/components/TagsList.vue')['default']
  }
}
